---
# tasks file for webserver


- name: install httpd package
  package:
      name: "httpd"
      state: present
  register: x

- name: document root dir
  file:
      state: directory
      dest:  "{{ dcdir }}"
  register: y
  tags: webgit

- name: conf web server
  template:
     dest: /etc/httpd/conf.d/web.conf
     src: templates/localconf.conf.j2
  when: x.rc == 0
  tags: webconf
  notify: service httpd


- name: copy web page from url
  get_url:
      dest: "{{ dcdir }}"
      url: "https://raw.githubusercontent.com/18uec075/webdata/master/index.html"
  when: y.failed ==  false
  tags: webgit

- name: start service for web
  service:
      name: "httpd"
      state: started
      #- name : Stop firewalld
      #  firewalld:
      #          immediate: yes
      #   port: 81
      #   state: a

